# MITRE ATT&CK Cheat Sheet: Detection Engineering Interviews

Reference: [MITRE ATT&CK Enterprise matrix](https://attack.mitre.org/matrices/enterprise/) (v19). Tactic = why (goal) · Technique = how (method) · Sub-technique = specific variant · Procedure = a named actor or tool using it.

| Tactic | Technique | Sub-techniques | Procedure | Detection | Mitigation |
|---|---|---|---|---|---|
| [Initial Access](https://attack.mitre.org/tactics/TA0001) | [**T1190** Exploit Public-Facing Application](https://attack.mitre.org/techniques/T1190/) | None | APT29 (Citrix, Pulse Secure, FortiGate, Zimbra flaws)<br>ShadowRay (exposed Ray servers)<br>Anthropic AI-orchestrated campaign (SSRF exploit) | Crafted requests in web/WAF logs<br>Spike in 4xx/5xx errors<br>Web server process spawning a shell or curl/wget<br>Outbound connection to a new host | WAF<br>Patch external apps quickly<br>Restrict outbound traffic from public servers<br>Segment the DMZ<br>Scan the external attack surface |
| [Initial Access](https://attack.mitre.org/tactics/TA0001) | [**T1566** Phishing](https://attack.mitre.org/techniques/T1566/) | .001 Spearphishing Attachment<br>.002 Spearphishing Link<br>.003 Spearphishing via Service<br>.004 Spearphishing Voice | APT28, APT29 (spearphishing links and attachments)<br>Scattered Spider (voice phishing) | Office or PDF reader spawning a shell or script<br>Email gateway and URL-click logs (new or lookalike domains)<br>Risky attachment types (ISO, LNK, macro-enabled docs)<br>New OAuth consent right after a click | Email filtering and attachment sandboxing<br>Block macros and risky file types<br>User training with an easy report button<br>Phishing-resistant MFA |
| [Initial Access](https://attack.mitre.org/tactics/TA0001)<br>[Persistence](https://attack.mitre.org/tactics/TA0003)<br>[Privilege Escalation](https://attack.mitre.org/tactics/TA0004)<br>[Stealth](https://attack.mitre.org/tactics/TA0005) | [**T1078** Valid Accounts](https://attack.mitre.org/techniques/T1078/) | .001 Default Accounts<br>.002 Domain Accounts<br>.003 Local Accounts<br>.004 Cloud Accounts | Volt Typhoon (valid credentials for persistence)<br>Akira, BlackByte, Play (VPN credentials)<br>FIN10 (single-factor VPN) | The login is legitimate, so check context: unusual source, time, logon type or geography<br>Service account logging in interactively<br>Impossible travel<br>Repeated MFA prompts<br>Cloud: access key used from a new IP (CloudTrail) | MFA<br>Conditional access<br>Disable legacy authentication<br>Remove unused accounts |
| [Execution](https://attack.mitre.org/tactics/TA0002) | [**T1059** Command and Scripting Interpreter](https://attack.mitre.org/techniques/T1059/) | .001 PowerShell<br>.003 Windows Command Shell<br>.004 Unix Shell<br>.006 Python<br>.009 Cloud API<br>(13 in total) | Empire (PowerShell framework)<br>Cobalt Strike<br>APT29 | PowerShell script block logging (4104)<br>Encoded or obfuscated commands (-enc, IEX, download cradles)<br>Office, WMI or a browser spawning shells<br>AMSI events | Constrained Language Mode<br>Script block logging and AMSI<br>Application control (WDAC, AppLocker)<br>Limit admin rights |
| [Execution](https://attack.mitre.org/tactics/TA0002)<br>[Persistence](https://attack.mitre.org/tactics/TA0003)<br>[Privilege Escalation](https://attack.mitre.org/tactics/TA0004) | [**T1053** Scheduled Task/Job](https://attack.mitre.org/techniques/T1053/) | .002 At<br>.003 Cron<br>.005 Scheduled Task<br>.006 Systemd Timers<br>.007 Container Orchestration Job | HAFNIUM (Tarrask malware)<br>Chimera (persistence via scheduled task) | New task creation (Windows 4698 with auditing on, Task Scheduler log, schtasks /create in process logs)<br>Tasks running from user-writable paths<br>Tasks created remotely or by odd parents<br>Linux: new cron entries or systemd timers | Limit who can create tasks<br>Audit task creation<br>Application control on what tasks can launch<br>File integrity monitoring on cron and systemd paths |
| [Persistence](https://attack.mitre.org/tactics/TA0003)<br>[Privilege Escalation](https://attack.mitre.org/tactics/TA0004) | [**T1098** Account Manipulation](https://attack.mitre.org/techniques/T1098/) | .001 Additional Cloud Credentials<br>.002 Additional Email Delegate Permissions<br>.003 Additional Cloud Roles<br>.004 SSH Authorized Keys<br>.005 Device Registration<br>.006 Additional Container Cluster Roles<br>.007 Additional Local or Domain Groups | APT29 (added credentials to apps and service principals)<br>Scattered Spider (registered its own MFA devices) | Cloud audit: CreateAccessKey, AttachUserPolicy, PutUserPolicy, CreatePolicyVersion, PassRole misuse<br>IdP audit: new MFA method or device, role changes, new credentials on service principals<br>Windows: changes to privileged groups (4728, 4732, 4756)<br>Linux: authorized_keys changes | Least-privilege IAM<br>Alert on role and permission changes<br>Restrict who can register MFA devices<br>Just-in-time privileged access<br>Regular access reviews |
| [Stealth](https://attack.mitre.org/tactics/TA0005) | [**T1218** System Binary Proxy Execution](https://attack.mitre.org/techniques/T1218/) | .005 Mshta<br>.007 Msiexec<br>.010 Regsvr32<br>.011 Rundll32<br>(14 in total) | QakBot (rundll32, regsvr32)<br>Cobalt Strike (rundll32 to run payloads) | Rare parent-child pairs (Office spawning mshta)<br>rundll32, regsvr32 or mshta with remote URLs or odd arguments<br>Network connections started by these binaries<br>Binary running from an unusual path | Block or restrict unneeded LOLBins with application control<br>Attack surface reduction (ASR) rules<br>Command-line logging<br>Restrict script hosts |
| [Defense Impairment](https://attack.mitre.org/tactics/TA0112) | [**T1685** Disable or Modify Tools](https://attack.mitre.org/techniques/T1685/) | .001 Disable or Modify Windows Event Log<br>.002 Disable or Modify Cloud Log<br>.003 Modify or Spoof Tool UI<br>.004 Disable or Modify Linux Audit System Log<br>.005 Clear Windows Event Logs<br>.006 Clear Linux or Mac System Logs | TeamTNT (disabled cloud monitoring agents)<br>APT41 (ETW bypass)<br>BlackByte (disabled Defender and Raccine) | Windows: log cleared (1102, 104), security services stopped<br>Cloud: StopLogging, DeleteTrail, UpdateTrail (CloudTrail); DeleteDetector or DisableGuardDuty<br>Linux: auditd or syslog stopped<br>A host that suddenly goes silent (expected telemetry missing) | EDR tamper protection<br>Restrict who can stop services or change logging config<br>Heartbeat checks that every agent reports in<br>Forward logs off-host in near real time |
| [Credential Access](https://attack.mitre.org/tactics/TA0006) | [**T1110** Brute Force](https://attack.mitre.org/techniques/T1110/) | .001 Password Guessing<br>.002 Password Cracking<br>.003 Password Spraying<br>.004 Credential Stuffing | Fox Kitten (RDP)<br>Chaos, Kinsing (SSH)<br>CrackMapExec (network sweep) | Many failed logons (Windows 4625, sshd, IdP) followed by a success<br>Guessing: many failures on one account<br>Spraying: few failures across many accounts<br>Stuffing: many accounts, mostly unique passwords, distributed IPs | MFA<br>Lockout and conditional access<br>Password policy<br>Reset known-breached accounts |
| [Credential Access](https://attack.mitre.org/tactics/TA0006) | [**T1003** OS Credential Dumping](https://attack.mitre.org/techniques/T1003/) | .001 LSASS Memory<br>.002 Security Account Manager<br>.003 NTDS<br>.004 LSA Secrets<br>.005 Cached Domain Credentials<br>.006 DCSync<br>.007 Proc Filesystem<br>.008 /etc/passwd and /etc/shadow | Mimikatz (LSASS, DCSync)<br>ProcDump, comsvcs.dll MiniDump (LSASS dumps)<br>Impacket secretsdump | Sysmon 10: process access to lsass.exe with suspicious access rights<br>Command lines like rundll32 comsvcs.dll MiniDump or procdump on lsass<br>New .dmp files from unusual processes<br>DCSync: directory replication requests (4662) from non-DC hosts | Credential Guard and LSA protection<br>ASR rule blocking credential stealing from LSASS<br>Limit local admin and debug privilege<br>Rotate credentials after exposure |
| [Credential Access](https://attack.mitre.org/tactics/TA0006) | [**T1558** Steal or Forge Kerberos Tickets](https://attack.mitre.org/techniques/T1558/) | .001 Golden Ticket<br>.002 Silver Ticket<br>.003 [Kerberoasting](https://attack.mitre.org/techniques/T1558/003/)<br>.004 AS-REP Roasting<br>.005 Ccache Files | Rubeus, Impacket (GetUserSPNs)<br>Empire and PowerSploit (Invoke-Kerberoast)<br>FIN7, Wizard Spider | Kerberoasting: event 4769 with RC4 encryption (etype 0x17)<br>One account requesting many service tickets in a short time<br>Service accounts targeted outside their baseline<br>Decoy service account with an SPN: any ticket request is suspicious | Enforce AES Kerberos encryption instead of RC4<br>Long (25+ character) service account passwords or gMSA<br>Least privilege for service accounts |
| [Credential Access](https://attack.mitre.org/tactics/TA0006) | [**T1621** Multi-Factor Authentication Request Generation](https://attack.mitre.org/techniques/T1621/) | None | APT29, Scattered Spider, LAPSUS$ (repeated MFA prompts) | Many MFA push requests or denials for one user in a short time<br>MFA challenges from IPs or locations that don't match the user<br>Repeated failed logins followed by MFA prompts<br>A push approved after several denials (IdP sign-in logs) | Number matching or phishing-resistant MFA instead of simple push<br>Limit MFA prompts per period<br>Conditional access on location and device<br>Train users to deny and report unexpected prompts |
| [Credential Access](https://attack.mitre.org/tactics/TA0006) | [**T1528** Steal Application Access Token](https://attack.mitre.org/techniques/T1528/) | None | APT28 (malicious OAuth apps posing as Google apps)<br>APT29 (stolen tokens instead of passwords)<br>Shai-Hulud, TeamPCP (CI/CD and cloud tokens) | New app registrations or consent grants with high-privilege scopes (mail read, offline access)<br>User consenting to an unverified or new app after a phishing link<br>Token used from new IPs or apps to read mail, calendar or SharePoint<br>Cloud or container token pulled from the metadata service, then used elsewhere | Block end-user consent, require admin approval<br>Audit OAuth apps and their permissions<br>Least-privilege roles and short-lived tokens<br>User training on consent prompts |
| [Lateral Movement](https://attack.mitre.org/tactics/TA0008) | [**T1021** Remote Services](https://attack.mitre.org/techniques/T1021/) | .001 Remote Desktop Protocol<br>.002 SMB/Windows Admin Shares<br>.003 Distributed Component Object Model<br>.004 SSH<br>.005 VNC<br>.006 Windows Remote Management<br>.007 Cloud Services<br>.008 Direct Cloud VM Connections | Medusa Group (valid accounts plus PsExec)<br>FIN5, Fox Kitten (valid credentials over RDP, VNC, VPN) | Logons 4624 type 3 (network) and type 10 (RDP), 4648 explicit credentials<br>SMB admin share access (5140, 5145), remote service creation (7045)<br>New source-to-destination pairs<br>One host authenticating to many hosts in a short window | Segment the network, block workstation-to-workstation SMB and RDP<br>MFA and just-in-time admin access<br>Disable unused remote services<br>Unique local admin passwords (LAPS) |
| [Collection](https://attack.mitre.org/tactics/TA0009) | [**T1530** Data from Cloud Storage](https://attack.mitre.org/techniques/T1530/) | None | Pacu (enumerates and downloads S3 data)<br>Scattered Spider (enumerated cloud data)<br>ShinyHunters (insecure buckets) | S3 data events: bulk GetObject or ListBucket by one identity<br>Spike in object access from a new IAM user or role, then transfer to external IPs<br>OAuth token granted to an external app, then high-volume downloads<br>Bucket policy or public-access changes | Audit permissions, block public access<br>Least-privilege IAM, temporary credentials<br>MFA and IP allowlisting for data access<br>Encrypt data at rest |
| [Command and Control](https://attack.mitre.org/tactics/TA0011) | [**T1071** Application Layer Protocol](https://attack.mitre.org/techniques/T1071/) | .001 Web Protocols<br>.002 File Transfer Protocols<br>.003 Mail Protocols<br>.004 DNS<br>.005 Publish/Subscribe Protocols | TeamTNT, Siloscape (IRC C2)<br>Velvet Ant (reverse SSH tunnels)<br>Sliver (WireGuard) | Regular beacon intervals (with jitter)<br>Unbalanced flows<br>Odd process speaking HTTP or DNS<br>Irregular ports<br>Long or high-entropy DNS names, TXT-heavy lookups, high NXDOMAIN rate (DGA) | Filter network traffic<br>Network intrusion prevention |
| [Exfiltration](https://attack.mitre.org/tactics/TA0010) | [**T1567** Exfiltration Over Web Service](https://attack.mitre.org/techniques/T1567/) | .001 Exfiltration to Code Repository<br>.002 Exfiltration to Cloud Storage<br>.003 Exfiltration to Text Storage Sites<br>.004 Exfiltration Over Webhook | Rclone (bulk sync to cloud storage)<br>StealBit (LockBit's exfiltration tool) | Large or unusual outbound volume to cloud storage, paste or webhook domains, especially from servers or non-browser processes<br>Sync tools like rclone appearing on hosts<br>Personal cloud accounts on corporate devices<br>Off-hours bulk transfers | Data loss prevention and egress filtering<br>Block unsanctioned cloud storage and webhooks<br>Proxy visibility (TLS inspection where appropriate)<br>Least privilege to sensitive data |
| [Impact](https://attack.mitre.org/tactics/TA0040) | [**T1486** Data Encrypted for Impact](https://attack.mitre.org/techniques/T1486/) | None | LockBit, Ryuk, REvil (ransomware families)<br>Akira, Play (ransomware groups) | Mass file renames or modifications, new extensions, high-entropy writes<br>Ransom notes dropped<br>Shadow copy and backup deletion (vssadmin, wbadmin, bcdedit)<br>Security tools disabled just before encryption<br>Canary file changes | Offline or immutable backups with tested restores<br>Endpoint behavior blocking of mass encryption<br>Segmentation and least privilege<br>Rapid host-isolation playbook |
| [Impact](https://attack.mitre.org/tactics/TA0040) | [**T1498** Network Denial of Service](https://attack.mitre.org/techniques/T1498/) | .001 Direct Network Flood<br>.002 Reflection Amplification | APT28 (DDoS on World Anti-Doping Agency, 2016)<br>Lucifer (TCP, UDP and HTTP floods) | Link saturation and packet-rate spikes in NetFlow<br>Traffic from amplification ports<br>Source side: a host sending huge outbound volume or running hping3 | Filter upstream at the ISP, CDN or DoS-mitigation provider |

**Notes**
- ATT&CK v19 renamed Defense Evasion to Stealth and added Defense Impairment. Older guides cite T1562 (Impair Defenses) for the behavior now under T1685.
- Each linked technique page lists its official mitigation IDs (M-numbers), MITRE's detection strategy (DET IDs) and more procedure examples.

*Contains material derived from MITRE ATT&CK®, a registered trademark of The MITRE Corporation. Source: https://attack.mitre.org (ATT&CK v19).*
